apiVersion: v1
kind: Service
metadata:
  name: hashresponse-svc
spec:
  type: ClusterIP
  selector:
    app: hashresponse
# let's TCP trafic from port 2345 to port 3000
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 3000
